name: Automatic Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Glowman554/setup-nasm@v1
    - name: setup
      run: sudo apt install genisoimage
    - name: Install PIL
      run: sudo pip3 install Pillow
    - name: make
      run: make iso
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: cdrom.iso 
